# docker-compose.yml

version: '3.5'

services:

  bitlbee:
    container_name: bitlbee
    restart: unless-stopped
    build: .
    image: facepalm/bitlbee:latest
    labels:
      - "traefik.enable=false"
    ports:
      - 127.0.0.1:${EXTERNAL_PORT}:6667
    networks:
      - bitlbee

networks:
  bitlbee:
    name: bitlbee
