# docker-compose.yml

version: '3'

services:

  bitlbee:
    container_name: bitlbee
    restart: unless-stopped
    build: .
    labels:
      - "traefik.enable=false"
    volumes:
      - ${STORAGE}:/var/lib/bitlbee:z
    ports:
      - 127.0.0.1:${EXTERNAL_PORT}:6667
